# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    yarn install
    yarn build
  displayName: 'yarn install and build'

- script: |
    echo "checkout to dist branch"
    git checkout --orphan $TARGET_BRANCH
    git rm -rf .
    rm -rf node_modules
    mv .vuepress/dist/* .
    git add -f --ignore-errors --all
    git -c user.name='azure pipeline' -c user.email='azure' commit -m ":tada: release ui"
    git push -f -q https://$GH_USER:$GH_TOKEN@github.com/$BUILD_REPOSITORY_ID $TARGET_BRANCH
  displayName: Publish to dist branch
